[2020-12-14 19:24:25,738] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -----------生成测试用例--------------
[2020-12-14 19:24:25,785] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成测试用例列表：['test_addfirm.py', 'test_firmlist.py', 'test_login.py']
[2020-12-14 19:24:25,785] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------- 开始执行用例----------------
[2020-12-14 19:24:25,787] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成接口自动化测试报告:2020_12_14-19_24_25_report.html
[2020-12-14 19:24:25,980] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_addfirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:24:25,980] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_deletefirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:24:25,981] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_firmlist (unittest.loader._FailedTest)执行错误
[2020-12-14 19:24:25,982] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例login.test_login (unittest.loader._FailedTest)执行错误
[2020-12-14 19:24:25,983] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------接口测试流程测试完成----------
[2020-12-14 19:24:25,986] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 删除过期的报告:True
[2020-12-14 19:25:53,069] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -----------生成测试用例--------------
[2020-12-14 19:25:53,104] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成测试用例列表：['test_addfirm.py', 'test_firmlist.py', 'test_login.py']
[2020-12-14 19:25:53,104] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------- 开始执行用例----------------
[2020-12-14 19:25:53,105] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成接口自动化测试报告:2020_12_14-19_25_53_report.html
[2020-12-14 19:25:53,217] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_addfirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:25:53,217] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_deletefirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:25:53,218] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_firmlist (unittest.loader._FailedTest)执行错误
[2020-12-14 19:25:53,218] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例login.test_login (unittest.loader._FailedTest)执行错误
[2020-12-14 19:25:53,219] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------接口测试流程测试完成----------
[2020-12-14 19:25:53,221] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 删除过期的报告:True
[2020-12-14 19:26:13,856] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -----------生成测试用例--------------
[2020-12-14 19:26:13,890] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成测试用例列表：['test_addfirm.py', 'test_firmlist.py', 'test_login.py']
[2020-12-14 19:26:13,890] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------- 开始执行用例----------------
[2020-12-14 19:26:13,891] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成接口自动化测试报告:2020_12_14-19_26_13_report.html
[2020-12-14 19:26:14,010] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_addfirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:26:14,011] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_deletefirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:26:14,011] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_firmlist (unittest.loader._FailedTest)执行错误
[2020-12-14 19:26:14,012] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例login.test_login (unittest.loader._FailedTest)执行错误
[2020-12-14 19:26:14,013] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------接口测试流程测试完成----------
[2020-12-14 19:26:14,014] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 删除过期的报告:True
[2020-12-14 19:26:37,505] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -----------生成测试用例--------------
[2020-12-14 19:26:37,557] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成测试用例列表：['test_addfirm.py', 'test_firmlist.py', 'test_login.py']
[2020-12-14 19:26:37,557] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------- 开始执行用例----------------
[2020-12-14 19:26:37,558] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成接口自动化测试报告:2020_12_14-19_26_37_report.html
[2020-12-14 19:26:37,696] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_addfirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:26:37,696] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_deletefirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:26:37,696] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_firmlist (unittest.loader._FailedTest)执行错误
[2020-12-14 19:26:37,696] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例login.test_login (unittest.loader._FailedTest)执行错误
[2020-12-14 19:26:37,698] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------接口测试流程测试完成----------
[2020-12-14 19:26:37,700] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 删除过期的报告:True
[2020-12-14 19:27:10,884] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -----------生成测试用例--------------
[2020-12-14 19:27:10,928] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成测试用例列表：['test_addfirm.py', 'test_firmlist.py', 'test_login.py']
[2020-12-14 19:27:10,929] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------- 开始执行用例----------------
[2020-12-14 19:27:10,930] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成接口自动化测试报告:2020_12_14-19_27_10_report.html
[2020-12-14 19:27:13,677] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (firm.test_addfirm.Test_AddFirm)执行成功
[2020-12-14 19:27:14,847] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_2 (firm.test_addfirm.Test_AddFirm)执行成功
[2020-12-14 19:27:14,848] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_deletefirm (unittest.loader._FailedTest)执行错误
[2020-12-14 19:27:16,081] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (firm.test_firmlist.Test_FirmList)执行成功
[2020-12-14 19:27:17,596] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (login.test_login.Test_login)执行成功
[2020-12-14 19:27:17,829] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_2 (login.test_login.Test_login)执行成功
[2020-12-14 19:27:17,830] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------接口测试流程测试完成----------
[2020-12-14 19:27:17,832] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 删除过期的报告:True
[2020-12-14 20:32:01,310] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -----------生成测试用例--------------
[2020-12-14 20:32:01,351] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成测试用例列表：['test_addfirm.py', 'test_firmlist.py', 'test_login.py']
[2020-12-14 20:32:01,352] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------- 开始执行用例----------------
[2020-12-14 20:32:01,353] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成接口自动化测试报告:2020_12_14-20_32_01_report.html
[2020-12-14 20:32:09,206] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (firm.test_addfirm.Test_AddFirm)执行成功
[2020-12-14 20:32:10,840] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_2 (firm.test_addfirm.Test_AddFirm)执行成功
[2020-12-14 20:32:10,841] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例firm.test_deletefirm (unittest.loader._FailedTest)执行错误
[2020-12-14 20:32:12,181] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (firm.test_firmlist.Test_FirmList)执行成功
[2020-12-14 20:32:13,452] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (login.test_login.Test_login)执行成功
[2020-12-14 20:32:13,677] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_2 (login.test_login.Test_login)执行成功
[2020-12-14 20:32:13,677] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------接口测试流程测试完成----------
[2020-12-14 20:32:13,679] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 删除过期的报告:True
[2020-12-14 20:32:40,962] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -----------生成测试用例--------------
[2020-12-14 20:32:40,994] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成测试用例列表：['test_addfirm.py', 'test_firmlist.py', 'test_login.py']
[2020-12-14 20:32:40,995] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------- 开始执行用例----------------
[2020-12-14 20:32:40,996] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 生成接口自动化测试报告:2020_12_14-20_32_40_report.html
[2020-12-14 20:32:42,588] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (firm.test_addfirm.Test_AddFirm)执行成功
[2020-12-14 20:32:43,703] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_2 (firm.test_addfirm.Test_AddFirm)执行成功
[2020-12-14 20:32:44,945] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (firm.test_firmlist.Test_FirmList)执行成功
[2020-12-14 20:32:46,054] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_1 (login.test_login.Test_login)执行成功
[2020-12-14 20:32:46,288] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 用例test_01_2 (login.test_login.Test_login)执行成功
[2020-12-14 20:32:46,289] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: -------接口测试流程测试完成----------
[2020-12-14 20:32:46,291] - C:\Users\pujun\Desktop\SAAS_API\lib\generate_logs.py] - INFO: 删除过期的报告:True
